services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    ports:
      - '3000:3000'
    env_file: .env.local

  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    env_file: .env.local
